--liquibase formatted sql
--changeset katsiaryna.silina@gmail.com:add-user-statuses-table splitStatements:true
CREATE TABLE SALON.DISCOUNT_STATUSES
(
    ID       INT AUTO_INCREMENT PRIMARY KEY,
    STATUS   VARCHAR(20)   NOT NULL,
    DISCOUNT DECIMAL(4, 1) NOT NULL DEFAULT 0.0,
    CONSTRAINT CHECK_STATUS_DISCOUNT CHECK (DISCOUNT BETWEEN 0.0 AND 100.0)
);

CREATE UNIQUE INDEX IDX_UN_DISCOUNT_STATUSES_STATUS ON SALON.DISCOUNT_STATUSES (STATUS);
--rollback DROP TABLE IF EXISTS SALON.DISCOUNT_STATUSES
