--liquibase formatted sql
--changeset katsiaryna.silina@gmail.com:add-users-table splitStatements:true
CREATE TABLE SALON.USERS
(
    ID                 INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME           VARCHAR(30)  NOT NULL,
    PASSWORD           VARCHAR(30)  NOT NULL,
    EMAIL              VARCHAR(100) NOT NULL,
    FIRST_NAME         VARCHAR(30)  NOT NULL,
    LAST_NAME          VARCHAR(30)  NOT NULL,
    DISCOUNT_STATUS_ID INT          NOT NULL DEFAULT 1,
    LAST_LOGIN         DATETIME              DEFAULT NOW(),
    ROLE_ID            INT          NOT NULL DEFAULT 1,
    USER_STATUS_ID     INT          NOT NULL DEFAULT 1,
    CONSTRAINT FK_USERS_DISCOUNT_STATUSES FOREIGN KEY (DISCOUNT_STATUS_ID) REFERENCES SALON.DISCOUNT_STATUSES (ID),
    CONSTRAINT FK_USERS_USER_ROLES FOREIGN KEY (ROLE_ID) REFERENCES SALON.USER_ROLES (ID),
    CONSTRAINT FK_USERS_USER_STATUSES FOREIGN KEY (USER_STATUS_ID) REFERENCES SALON.USER_STATUSES (ID)
);

CREATE UNIQUE INDEX IDX_UN_USERS_USER_NAME ON CAR_RENTAL.USERS (USERNAME);
CREATE UNIQUE INDEX IDX_UN_USERS_EMAIL ON CAR_RENTAL.USERS (EMAIL);
CREATE INDEX IDX_USERS_USER_ROLES ON SALON.USERS (ROLE_ID);
CREATE INDEX IDX_USERS_DISC_STATUSES ON SALON.USERS (DISCOUNT_STATUS_ID);
CREATE INDEX IDX_USERS_USER_STATUSES ON SALON.USERS (USER_STATUS_ID);
--rollback DROP TABLE IF EXISTS SALON.USERS
