--liquibase formatted sql
--changeset katsiaryna.silina@gmail.com:add-services-table splitStatements:true
CREATE TABLE SALON.SERVICES
(
    ID             INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NAME           VARCHAR(50) NOT NULL,
    IS_COMPLEX     CHAR(1)     NOT NULL DEFAULT 'N',
    MINUTES_NEEDED INT         NOT NULL,
    DESCRIPTION    TEXT        NOT NULL,
    PRICE          DECIMAL(10, 2),
    IS_DEPRECATED  CHAR(1)     NOT NULL DEFAULT 'N',
    CONSTRAINT CHECK_SERVICES_IS_DEPRECATED CHECK (IS_DEPRECATED IN ('Y', 'N')),
    CONSTRAINT CHECK_SERVICE_IS_COMPLEX CHECK (IS_COMPLEX IN ('Y', 'N'))
);

CREATE UNIQUE INDEX IDX_UN_SERVICES_NAME ON SALON.SERVICES (NAME);
--rollback DROP TABLE IF EXISTS SALON.SERVICES
