--liquibase formatted sql
--changeset katsiaryna.silina@gmail.com:add-order-feedbacks-table splitStatements:true
CREATE TABLE SALON.ORDER_FEEDBACKS
(
    ID          INT UNSIGNED PRIMARY KEY,
    MARK        TINYINT,
    FEEDBACK    TEXT,
    USER_ID     INT UNSIGNED NOT NULL,
    IS_VERIFIED CHAR(1) NOT NULL DEFAULT 'N',
    CONSTRAINT FK_ORDER_FEEDBACKS_USERS FOREIGN KEY (USER_ID) REFERENCES SALON.USERS (ID),
    CONSTRAINT CHECK_ORDER_FEEDBACKS_IS_VERIFIED CHECK (IS_VERIFIED IN ('Y', 'N')),
    CONSTRAINT MARK_COLUMN_POSITIVE CHECK (MARK BETWEEN 1 AND 5)
);
--rollback DROP TABLE IF EXISTS SALON.ORDER_FEEDBACKS
