--liquibase formatted sql
--changeset katsiaryna.silina@gmail.com:add-orders-table splitStatements:true
CREATE TABLE SALON.ORDERS
(
    ID                  INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_DATE_TIME     DATETIME NOT NULL DEFAULT NOW(),
    VISIT_DATE_TIME     DATETIME,
    USER_ID             INT      NOT NULL,
    ORDER_STATUS_ID     INT      NOT NULL,
    PRICE_WITH_DISCOUNT DOUBLE   NOT NULL,
    /*FEEDBACK_ID         INT      NOT NULL,
    CONSTRAINT FK_ORDERS_ORDER_FEEDBACKS FOREIGN KEY (FEEDBACK_ID) REFERENCES SALON.ORDER_FEEDBACKS (ID),
    */CONSTRAINT FK_ORDERS_USERS FOREIGN KEY (USER_ID) REFERENCES SALON.USERS (ID),
    CONSTRAINT FK_ORDERS_ORDER_STATUSES FOREIGN KEY (ORDER_STATUS_ID) REFERENCES SALON.ORDER_STATUSES (ID)
);

/*CREATE INDEX IDX_ORDERS_ORDER_FEEDBACKS ON SALON.ORDER_FEEDBACKS (ID);
*/CREATE INDEX IDX_ORDERS_USERS ON SALON.USERS (ID);
CREATE INDEX IDX_ORDERS_ORDER_STATUSES ON SALON.ORDER_STATUSES (ID);
--rollback DROP TABLE IF EXISTS SALON.ORDERS
