--liquibase formatted sql
--changeset katsiaryna.silina@gmail.com:add-orders-services-table splitStatements:true
CREATE TABLE SALON.ORDERS_SERVICES
(
    ORDER_ID   INT UNSIGNED NOT NULL,
    SERVICE_ID INT UNSIGNED NOT NULL,
    CONSTRAINT FK_ORDERS_SERVICES_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES SALON.ORDERS (ID),
    CONSTRAINT FK_ORDERS_SERVICES_SERVICES FOREIGN KEY (SERVICE_ID) REFERENCES SALON.SERVICES (ID)
);
CREATE INDEX IDX_ORDERS_SERVICES_ORDERS ON SALON.ORDERS_SERVICES (ORDER_ID);
CREATE INDEX IDX_ORDERS_SERVICES_SERVICES ON SALON.ORDERS_SERVICES (SERVICE_ID);
--rollback DROP TABLE IF EXISTS SALON.ORDERS_SERVICES
