--liquibase formatted sql
--changeset katsiaryna.silina@gmail.com:populate-users-table splitStatements:true
INSERT INTO SALON.USERS (USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, DISCOUNT_STATUS_ID, ROLE_ID, PHONE_NUMBER)
VALUES ('admin', '$2a$12$ClJ4jihN1cEXRuPZlke4t.9SPWvzFikIi4TxqLoU9yXmvZHGJwV9O', 'admin@gmail.com',
        'Alex', 'Stone', 5, 1, '+375293214');
INSERT INTO SALON.USERS (USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, DISCOUNT_STATUS_ID, ROLE_ID, PHONE_NUMBER)
VALUES ('client', '$2a$12$ClJ4jihN1cEXRuPZlke4t.9SPWvzFikIi4TxqLoU9yXmvZHGJwV9O', 'client@gmail.com',
        'Cli', 'Ent', 1, 2, '+325115290');
INSERT INTO SALON.USERS (USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, DISCOUNT_STATUS_ID, ROLE_ID, PHONE_NUMBER)
VALUES ('flash', '$2a$12$ClJ4jihN1cEXRuPZlke4t.9SPWvzFikIi4TxqLoU9yXmvZHGJwV9O', 'flash@mail.ru',
        'Artem', 'Point', 1, 2, '+32522629991');
INSERT INTO SALON.USERS (USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, DISCOUNT_STATUS_ID, ROLE_ID, PHONE_NUMBER)
VALUES ('eismont', '$2a$12$ClJ4jihN1cEXRuPZlke4t.9SPWvzFikIi4TxqLoU9yXmvZHGJwV9O', 'eismont@mail.ru',
        'Eismont', 'Li', 1, 2, '+34011623923');
INSERT INTO SALON.USERS (USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, DISCOUNT_STATUS_ID, ROLE_ID, PHONE_NUMBER)
VALUES ('lilia', '$2a$12$ClJ4jihN1cEXRuPZlke4t.9SPWvzFikIi4TxqLoU9yXmvZHGJwV9O', 'lilia_t@gmail.com',
        'Lilia', 'Tarasova', 1, 2, '+32344823300');
INSERT INTO SALON.USERS (USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, DISCOUNT_STATUS_ID, ROLE_ID, PHONE_NUMBER)
VALUES ('dark', '$2a$12$ClJ4jihN1cEXRuPZlke4t.9SPWvzFikIi4TxqLoU9yXmvZHGJwV9O', 'dark@gmail.com',
        'Dmitri', 'Uspenski', 1, 2, '+34523872988');
INSERT INTO SALON.USERS (USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, DISCOUNT_STATUS_ID, ROLE_ID, PHONE_NUMBER)
VALUES ('light', '$2a$12$ClJ4jihN1cEXRuPZlke4t.9SPWvzFikIi4TxqLoU9yXmvZHGJwV9O', 'atrurez@gmail.com',
        'Artur', 'Ivanov', 1, 2, '+34586817955');
INSERT INTO SALON.USERS (USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, DISCOUNT_STATUS_ID, ROLE_ID, PHONE_NUMBER)
VALUES ('billy', '$2a$12$ClJ4jihN1cEXRuPZlke4t.9SPWvzFikIi4TxqLoU9yXmvZHGJwV9O', 'billy@gmail.com',
        'Bill', 'Ho', 1, 2, '+3758321926');
INSERT INTO SALON.USERS (USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, DISCOUNT_STATUS_ID, ROLE_ID, PHONE_NUMBER)
VALUES ('ann', '$2a$12$ClJ4jihN1cEXRuPZlke4t.9SPWvzFikIi4TxqLoU9yXmvZHGJwV9O', 'ann@gmail.com',
        'Ann', 'Litvinova', 1, 2, '+3757121432');
INSERT INTO SALON.USERS (USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, DISCOUNT_STATUS_ID, ROLE_ID, PHONE_NUMBER)
VALUES ('sofya', '$2a$12$ClJ4jihN1cEXRuPZlke4t.9SPWvzFikIi4TxqLoU9yXmvZHGJwV9O', 'sofya@gmail.com',
        'Sofia', 'Blizka', 1, 2, '+3753321531');
INSERT INTO SALON.USERS (USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, DISCOUNT_STATUS_ID, ROLE_ID, PHONE_NUMBER)
VALUES ('vitia', '$2a$12$ClJ4jihN1cEXRuPZlke4t.9SPWvzFikIi4TxqLoU9yXmvZHGJwV9O', 'vitia@gmail.com',
        'Vitia', 'Solodko', 1, 2, '+3754422830');
