--liquibase formatted sql
--changeset katsiaryna.silina@gmail.com:add-visit-times-table splitStatements:true
CREATE TABLE SALON.VISIT_TIMES
(
    ID            INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    BEGIN_TIME    TIME    NOT NULL,
    END_TIME      TIME    NOT NULL,
    IS_DEPRECATED CHAR(1) NOT NULL DEFAULT 'N',
    CONSTRAINT CHECK_VISIT_TIME_IS_DEPRECATED CHECK (IS_DEPRECATED IN ('Y', 'N'))
);

CREATE INDEX IDX_VISIT_TIMES_BEGIN_TIME ON SALON.VISIT_TIMES (BEGIN_TIME);
CREATE INDEX IDX_VISIT_TIMES_END_TIME ON SALON.VISIT_TIMES (END_TIME);
--rollback DROP TABLE IF EXISTS SALON.VISIT_TIMES
