--liquibase formatted sql
--changeset katsiaryna.silina@gmail.com:populate-visit-times-table splitStatements:true
INSERT INTO SALON.VISIT_TIMES (BEGIN_TIME, END_TIME, IS_DEPRECATED)
VALUES ('9:00', '9:30', 'N');
INSERT INTO SALON.VISIT_TIMES (BEGIN_TIME, END_TIME, IS_DEPRECATED)
VALUES ('9:30', '10:00', 'N');
INSERT INTO SALON.VISIT_TIMES (BEGIN_TIME, END_TIME, IS_DEPRECATED)
VALUES ('10:00', '11:00', 'N');
INSERT INTO SALON.VISIT_TIMES (BEGIN_TIME, END_TIME, IS_DEPRECATED)
VALUES ('11:00', '11:30', 'N');
INSERT INTO SALON.VISIT_TIMES (BEGIN_TIME, END_TIME, IS_DEPRECATED)
VALUES ('11:30', '12:00', 'N');
INSERT INTO SALON.VISIT_TIMES (BEGIN_TIME, END_TIME, IS_DEPRECATED)
VALUES ('12:00', '12:30', 'N');
INSERT INTO SALON.VISIT_TIMES (BEGIN_TIME, END_TIME, IS_DEPRECATED)
VALUES ('12:30', '13:00', 'N');
INSERT INTO SALON.VISIT_TIMES (BEGIN_TIME, END_TIME, IS_DEPRECATED)
VALUES ('13:00', '13:30', 'N');
INSERT INTO SALON.VISIT_TIMES (BEGIN_TIME, END_TIME, IS_DEPRECATED)
VALUES ('13:30', '14:00', 'Y');
INSERT INTO SALON.VISIT_TIMES (BEGIN_TIME, END_TIME, IS_DEPRECATED)
VALUES ('14:00', '14:30', 'Y');
INSERT INTO SALON.VISIT_TIMES (BEGIN_TIME, END_TIME, IS_DEPRECATED)
VALUES ('14:30', '15:00', 'N');
INSERT INTO SALON.VISIT_TIMES (BEGIN_TIME, END_TIME, IS_DEPRECATED)
VALUES ('15:00', '15:30', 'N');
INSERT INTO SALON.VISIT_TIMES (BEGIN_TIME, END_TIME, IS_DEPRECATED)
VALUES ('15:30', '16:00', 'N');
INSERT INTO SALON.VISIT_TIMES (BEGIN_TIME, END_TIME, IS_DEPRECATED)
VALUES ('16:00', '16:30', 'N');
INSERT INTO SALON.VISIT_TIMES (BEGIN_TIME, END_TIME, IS_DEPRECATED)
VALUES ('16:30', '17:00', 'N');
INSERT INTO SALON.VISIT_TIMES (BEGIN_TIME, END_TIME, IS_DEPRECATED)
VALUES ('17:00', '17:30', 'N');
INSERT INTO SALON.VISIT_TIMES (BEGIN_TIME, END_TIME, IS_DEPRECATED)
VALUES ('17:30', '18:00', 'N');
INSERT INTO SALON.VISIT_TIMES (BEGIN_TIME, END_TIME, IS_DEPRECATED)
VALUES ('18:00', '18:30', 'N');
INSERT INTO SALON.VISIT_TIMES (BEGIN_TIME, END_TIME, IS_DEPRECATED)
VALUES ('18:30', '19:00', 'N');
INSERT INTO SALON.VISIT_TIMES (BEGIN_TIME, END_TIME, IS_DEPRECATED)
VALUES ('19:00', '19:10', 'N');
INSERT INTO SALON.VISIT_TIMES (BEGIN_TIME, END_TIME, IS_DEPRECATED)
VALUES ('19:30', '20:00', 'N');
INSERT INTO SALON.VISIT_TIMES (BEGIN_TIME, END_TIME, IS_DEPRECATED)
VALUES ('20:00', '20:30', 'N');
INSERT INTO SALON.VISIT_TIMES (BEGIN_TIME, END_TIME, IS_DEPRECATED)
VALUES ('20:30', '21:50', 'N');
INSERT INTO SALON.VISIT_TIMES (BEGIN_TIME, END_TIME, IS_DEPRECATED)
VALUES ('13:50', '14:10', 'N');
